### ISSUE TITLE
RunImage on Windows ?

### ISSUE THREAD

**Issue by fwn0** [VHSgunzo/runimage#5]
purely teorethical - is it possible to swap your runimage into RAM (tmpfs) and create your own running linux in windows ?
There exists userspace driver for Windows (FUSE) and here tmpfs for Windows / memefs ( https://github.com/Ceiridge/WinFsp-MemFs-Extended ). I do not use Windows for over 7 years, but for my friends on Windows ( who constantly whine and complain about Windows ) would certainly be interesting to show a beautiful, easy a secure Linux under Windows, running from your runimage.

**Comment by VHSgunzo** [comment]
@fwn0 RunImage requires a loaded Linux kernel and at the moment the only way close to native to run RunImage in Windows is WSL 2 and preferably on Windows 11, because it is the most functional there. But you can also use virtual machines.
